### PR TITLE
readme: Update dependencies and mention local sharing

### PR DESCRIPTION
**Pull request by dcz-purism**
Fulfilling the second request from https://github.com/zeenix/gps-share/issues/24#issuecomment-818672806

### CODE REVIEW

**Review by zeenix — APPROVED** [review]
Thanks. We should also mention the transports supported and the CLI args (the former could be part of the latter).

**Comment by dcz-purism** [comment]
I've rebased and added a section about command line arguments. I wasn't really sure how that should be different from `--help` output, so I just reworded it slightly.

**Comment by zeenix** [comment]
Great this is good enough. I'll try and rollout a crates.io release soon.

**Comment by zeenix** [comment]
@dcz-purism Seems the [CI on master is failing](https://travis-ci.org/github/zeenix/gps-share/builds/768679637). Could you please have a look?

**Comment by dcz-purism** [comment]
I tried to fix this here: https://github.com/zeenix/gps-share/pull/27

**Pull request merged**
