### PR TITLE
Local socket support

### PR DESCRIPTION
**Pull request by dcz-purism**
I don't have access to the branch from https://github.com/zeenix/gps-share/pull/18, so opened again while addressing comments and resolving conflicts.

### CODE REVIEW

**Comment by zeenix** [comment]
Cool, have you tested it?

**Comment by dcz-purism** [comment]
Not very rigorously - I don't have a GPS device attached here. A socket does get created when run.

**Comment by zeenix** [comment]
> Not very rigorously - I don't have a GPS device attached here. A socket does get created when run.

The unix socket part I'm hoping was already tested by @nytowl. It's the new TCP part I'd like you to test before I can merge. I'd suggest you get your hands on a GPS device if you'd want to work on gps-share. :)

**Comment by dcz-purism** [comment]
Well, the GPS part was not touched, so there's nothing learned from getting a GPS device. All that is needed to test the new thread is the thread part, and I have tested that indeed we still do have both a local and a network socket with the `-` GPS device. I'm not sure if I can gain anything by testing a GPS connection here.

If integration tests are an option, I guess that would be one step up from the current situation.

**Comment by zeenix** [comment]
> Well, the GPS part was not touched, so there's nothing learned from getting a GPS device.

Sorry for not being clear. I meant in general you'd need a GPS device if you'll be working on this project. :)

> All that is needed to test the new thread is the thread part, and I have tested that indeed we still do have both a local and a network socket with the `-` GPS device.

Cool. That's good for now. Thanks.

> If integration tests are an option, I guess that would be one step up from the current situation.

Sure thing, if you'd like to contribute those, it'd be awesome. Please keep in mind I wrote the project (3-4 years ago) when I was completely new to Rust so if I had the time, I'd rewrite it.

**Comment by dcz-purism** [comment]
Oh, I have no shortage of GPS devices :) Glad that you're open to rewriting, I'm not a fan of how object-oriented some things look :)

**Pull request merged**
