### PR TITLE
Implement GitHub Actions

### LINKED ISSUE #28: Move from Travis CI to GH Actions
travis-ci.org is going away soon and GH actions is superior anyway so should move the CI to that.

cc @dcz-purism @nytowl.

### PR DESCRIPTION
**Pull request by andrew-stclair**
Implementing GitHub actions to build and test gps-share binaries

Tests are built on every push

Releases are built on each tag and are uploaded to a GitHub release

fixes #28

### CODE REVIEW

**Review by zeenix — CHANGES_REQUESTED** [review]
Thanks so much. Looks good apart from some minor stuff. Also a typo in the first commit message title.

**Comment by zeenix** [comment]
@andrew-stclair what happened? You were so close.

**Comment by andrew-stclair** [comment]
Ah, i think during my squashing, i broke something. I'll recreate a pull request once i've implemented your suggestions

**Comment by andrew-stclair** [comment]
Opened new Pull Request in #33 

Sorry, i do know git, but not that well.

**Pull request closed without merging**
